apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  labels:
    tekton.dev/pipeline: azureml-container
  generateName: azureml-container-tensorflow-housing-
spec:
  params:
  - name: model-name
    value: tensorflow-housing
  - name: model-version
    value: "1"
  - name: aws-bucket-name
    value: rhoai-edge-models
  - name: gitServer
    value: https://github.com
  - name: gitOrgName
    value: opendatahub-io
  - name: gitRepoName
    value: ai-edge
  - name: containerfileRelativePath
    value: pipelines/containerfiles/Containerfile.openvino.mlserver.mlflow
  pipelineRef:
    name: azureml-container
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
  - name: buildah-cache
    persistentVolumeClaim:
      claimName: buildah-cache-pvc
  - name: aws-secret
    secret:
        secretName: aws-env
