apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: azureml-container
spec:
  params:
  - name: model-name
    type: string
  - default: "1"
    name: model-version
    type: string
  - name: aws-bucket-name
    type: string
  - name: gitServer
    type: string
  - name: gitOrgName
    type: string
  - name: gitRepoName
    type: string
  - name: containerfileRelativePath
    type: string
  tasks:
  - name: kserve-download-model
    params:
    - name: model-name
      value: $(params.model-name)
    - name: current-namespace
      value: $(context.pipelineRun.namespace)
    - name: aws-bucket-name
      value: $(params.aws-bucket-name)
    taskRef:
      kind: Task
      name: kserve-download-model
    workspaces:
    - name: workspace
      workspace: buildah-cache
    - name: aws-secret
      workspace: aws-secret
  - name: git-clone-containerfile-repo
    params:
      - name: url
        value: $(params.gitServer)/$(params.gitOrgName)/$(params.gitRepoName)
      - name: gitInitImage
        value: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:1a50511583fc02a27012d17d942e247813404104ddd282d7e26f99765174392c
      - name: subdirectory
        value: /containerfile_repo/
    runAfter:
      - kserve-download-model
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
      - name: output
        workspace: buildah-cache
      - name: basic-auth
        workspace: git-basic-auth
  - name: check-model-and-containerfile-exists
    params:
    - name: model-name
      value: $(params.model-name)
    - name: containerfilePath
      value: containerfile_repo/$(params.containerfileRelativePath)
    - name: current-namespace
      value: $(context.pipelineRun.namespace)
    runAfter:
      - git-clone-containerfile-repo
    taskRef:
      kind: Task
      name: check-model-and-containerfile-exists
    workspaces:
    - name: workspace
      workspace: buildah-cache
  - name: create-imagestream
    params:
    - name: SCRIPT
      value: oc create imagestream $(params.model-name)  --lookup-local=true --dry-run=client
        -o yaml | oc apply -f -
    - name: VERSION
      value: latest
    runAfter:
     - check-model-and-containerfile-exists
    taskRef:
      kind: ClusterTask
      name: openshift-client
  - name: build-mlflow-container
    params:
    - name: IMAGE
      value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(params.model-name):$(params.model-version)
    - name: BUILDER_IMAGE
      value: registry.redhat.io/rhel8/buildah@sha256:0a86ecbdfbe86e9d225b7fe4b090a0dd6d323f8afdfdf2bd933ff223ddb53320
    - name: STORAGE_DRIVER
      value: vfs
    - name: DOCKERFILE
      value: containerfile_repo/$(params.containerfileRelativePath)
    - name: CONTEXT
      value: $(params.model-name)
    - name: TLSVERIFY
      value: "true"
    - name: FORMAT
      value: oci
    - name: BUILD_EXTRA_ARGS
      value: "--build-arg MODEL_NAME=$(params.model-name)"
    - name: SKIP_PUSH
      value: "false"
    runAfter:
    - create-imagestream
    taskRef:
      kind: ClusterTask
      name: buildah
    workspaces:
    - name: source
      workspace: buildah-cache
  workspaces:
  - name: buildah-cache
  - name: aws-secret
  - name: git-basic-auth
