apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kserve-download-model
spec:
  description: This Task can be used to a download a model
  params:
  - name: model-name
    type: string
  - name: current-namespace
    default: "default"
    type: string
  - name: s3-bucket-name
    type: string
  results:
  - name: s3-url
    description: The S3 URL used to download the model
  steps:
  - name: download-model-s3
    image: quay.io/opendatahub/kserve-storage-initializer:v0.11
    script: |
      mkdir -p $(workspaces.workspace.path)/model_dir/

      export S3_URL="s3://$(params.s3-bucket-name)/$(params.model-name)"
      echo -n $S3_URL | tee $(results.s3-url.path) ;

      STORAGE_CONFIG="$(cat $(workspaces.s3-secret.path)/s3-storage-config)" /storage-initializer/scripts/initializer-entrypoint \
      $S3_URL \
      $(workspaces.workspace.path)/model_dir/$(params.model-name)
  workspaces:
  - description: The workspace for the downloaded model.
    name: workspace
  - description: The S3 secret.
    name: s3-secret
