apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: retrieve-build-image-info
spec:
  description: Return information about the built image
  params:
  - name: namespace
    type: string
  - name: model-name
    type: string
  - name: model-version
    type: string
  - name: buildah-sha
    type: string
  - name: pipeline-run-uid
    type: string
  - name: target-image-tag-references
    type: array
  workspaces:
  - name: images-url
  steps:
  - name: get-image-sha
    image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
    args:
      - "$(params.target-image-tag-references[*])"
    script: |
      #!/usr/bin/env bash

      set -Eeuo pipefail

      echo -n "$(params.model-name)" | tee $(results.model-name.path) ;
      echo ;
      echo -n "$(params.model-version)" | tee $(results.model-version.path) ;
      echo ;
      export DOCKER_IMAGE_REF=$(oc get -n $(params.namespace) -o jsonpath='{.image.dockerImageReference}' imagestreamtag/$(params.model-name):$(params.model-version)) ;
      if [[ $DOCKER_IMAGE_REF != *"$(params.buildah-sha)"* ]]; then
        echo "ImageStreamTag doesn't contain the correct image SHA"
        exit 1 ;
      fi
      echo -n $DOCKER_IMAGE_REF | tee $(results.internal-image-url.path) ;
      echo ;
      oc get -n $(params.namespace) -o jsonpath='{.image.dockerImageMetadata.Size}' imagestreamtag/$(params.model-name):$(params.model-version) | tee $(results.internal-image-size.path) ;
      echo ;
      oc get -n $(params.namespace) -o jsonpath='{.image.dockerImageMetadata.Created}' imagestreamtag/$(params.model-name):$(params.model-version) | tee $(results.internal-image-created-at.path) ;
      echo ;
      oc get -n $(params.namespace) -o jsonpath='{.image.dockerImageMetadata.Config.Labels.io\.buildah\.version}' imagestreamtag/$(params.model-name):$(params.model-version) | tee $(results.internal-image-buildah-version.path) ;
      echo ;
      echo -n "$@" | tee $(results.target-image-tag-references.path) ;
  - name: build-urls-txt
    image: registry.access.redhat.com/ubi9/ubi-micro
    args:
      - "$(params.target-image-tag-references[*])"
    script: |
      #!/usr/bin/env bash

      set -Eeuo pipefail

      # The skopeo-copy task looks for this file in its workspace if the source and destination parameters are
      # empty. This is what allows pushing to more than one tag from the single taskrun.
      export URLTXT=$(workspaces.images-url.path)/url.txt
      export SOURCE_IMAGE_REF=$(cat $(results.internal-image-url.path))

      rm -f ${URLTXT}
      for target in "$@"; do
        echo "docker://${SOURCE_IMAGE_REF} docker://${target}" >> "${URLTXT}"
      done

      echo "Contents of ${URLTXT}:"
      cat ${URLTXT}
  results:
  - name: model-name
    description: The name of the model
  - name: model-version
    description: The version of the model
  - name: internal-image-size
    description: The size of the image
  - name: internal-image-created-at
    description: The date and time the image was created in UTC format
  - name: internal-image-buildah-version
    description: The version of buildah used to build the image
  - name: internal-image-url
    description: The url of the image in the internal registry
  - name: target-image-tag-references
    description: The fully qualified image reference that the image was pushed to (e.g. registry.example.com/my-org/ai-model:1.0-1)
