apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: tensorflow-housing-app
    - op: replace
      path: /spec/source/path
      value: acm/odh-edge/apps/tensorflow-housing-app
    - op: replace
      path: /spec/destination/namespace
      value: tensorflow-housing-app
  target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
- patch: |-
    - op: replace
      path: /metadata/name
      value: tensorflow-housing-app
  target:
    version: v1
    kind: Namespace
