apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  labels:
    tekton.dev/pipeline: build-container-image
  generateName: build-container-image-bike-rentals-
spec:
  params:
  - name: model-name
    value: bike-rentals-auto-ml
  - name: model-version
    value: "1"
  - name: aws-bucket-name
    value: rhoai-edge-models
  - name: gitServer
    value: https://github.com
  - name: gitOrgName
    value: opendatahub-io
  - name: gitRepoName
    value: ai-edge
  - name: containerfileRelativePath
    value: pipelines/containerfiles/Containerfile.seldonio.mlserver.mlflow
  - name: fetch-model
    value: "git"
  - name: git-model-repo
    value: https://github.com/opendatahub-io/ai-edge.git
  - name: modelRelativePath
    value: pipelines/models/
  - name: git-revision
    value: "main"
  pipelineRef:
    name: build-container-image
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
  - name: model-workspace
    persistentVolumeClaim:
      claimName: basic-pvc
  - name: buildah-cache
    persistentVolumeClaim:
      claimName: buildah-cache-pvc
  - name: aws-secret
    secret:
        secretName: aws-env
