apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - multiclusterobservability.yaml

configMapGenerator:
  - name: grafana-dashboard-edge-inference-health
    files:
    - grafana-dashboards/edge-inference-health.json
    options:
      annotations:
        observability.open-cluster-management.io/dashboard-folder: "Edge"
      labels:
        grafana-custom-dashboard: "true"
  - name: grafana-dashboard-edge-inference-metrics-housing-and-binking
    files:
    - grafana-dashboards/inference-metrics-housing-and-biking-app.json
    options:
      annotations:
        observability.open-cluster-management.io/dashboard-folder: "Edge"
      labels:
        grafana-custom-dashboard: "true"

secretGenerator:
- name: thanos-object-storage
  files:
  - secrets/thanos.yaml
  options:
    disableNameSuffixHash: true
