apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: gitops-update-pipeline-bike-rentals-
  labels:
    tekton.dev/pipeline: gitops-update-pipeline
spec:
  params:
  - name: gitServer
    value: http://gitea-ai-edge-rhoai-edge-acm.apps.rhoai-edge-acm-poc.rhaiseng.com
  - name: gitOrgName
    value: edge-user-1
  - name: gitRepoName
    value: ai-edge-gitops
  - name: imageDigest
    value: sha256:723521f61d4770c50e7952df66a21ffbe6d37e648dd60e6f2106483ef99235b8
  - name: imageReferenceFilePath
    value: acm/odh-edge/apps/bike-rental-app/kustomization.yaml
  - name: gitTokenSecretName
    value: gitea-edge-user-1
  pipelineRef:
    name: gitops-update-pipeline
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
  - name: git-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: git-basic-auth
    secret:
      secretName: gitea-edge-user-1
