apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: gitops-update-pipeline-bike-rentals-
  labels:
    tekton.dev/pipeline: gitops-update-pipeline
spec:
  params:
  - name: gitServer
    value: https://github.com
  - name: gitApiServer
    value: api.github.com
  - name: gitOrgName
    value: username
  - name: gitRepoName
    value: ai-edge-gitops
  - name: gitRepoBranchBase
    value: main
  - name: imageDigest
    value: sha256:22590bbf246cd231abebc13d7b20761b7f70e614dca9e430a1069510bdba2820
  - name: imageReferenceFilePath
    value: acm/odh-edge/apps/bike-rental-app/kustomization.yaml
  - name: gitTokenSecretName
    value: edge-user-1
  pipelineRef:
    name: gitops-update-pipeline
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
  - name: git-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: git-basic-auth
    secret:
      secretName: edge-user-1
