apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

# When authenticated Channel is required, set the user and accessToken,
# and uncomment this section and the replacements section below
#secretGenerator:
#- name: git-credentials
#  literals:
#  - user=username
#  - accessToken=access_token

namespace: tensorflow-housing-app
namePrefix: tensorflow-housing-app-

commonAnnotations:
  apps.open-cluster-management.io/git-path: acm/odh-edge/apps/tensorflow-housing-app

replacements:
- source:
    kind: Placement
    group: cluster.open-cluster-management.io
    fieldPath: metadata.name
  targets:
  - select:
      group: apps.open-cluster-management.io
      kind: Subscription
    fieldPaths:
      - spec.placement.placementRef.name
#- source:
#    kind: Secret
#    name: git-credentials
#    fieldPath: metadata.name
#  targets:
#  - select:
#      group: apps.open-cluster-management.io
#      kind: Channel
#    fieldPaths:
#      - spec.secretRef.name
#    options:
#      create: true

# Can't do this as a "replacement", as needs to be of form namespace/name
patches:
- patch: |-
    - op: replace
      path: /spec/channel
      value: tensorflow-housing-app/tensorflow-housing-app-channel
  target:
    kind: Subscription
- patch: |-
    - op: replace
      path: /spec/pathname
      value: https://github.com/opendatahub-io/ai-edge
  target:
    kind: Channel
