apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: bike-rental-app
namePrefix: bike-rental-app-

commonAnnotations:
  apps.open-cluster-management.io/git-path: acm/odh-edge/apps/bike-rental-app

replacements:
- source:
    kind: Placement
    group: cluster.open-cluster-management.io
    fieldPath: metadata.name
  targets:
  - select:
      group: apps.open-cluster-management.io
      kind: Subscription
    fieldPaths:
      - spec.placement.placementRef.name

# Can't do this as a "replacement", as needs to be of form namespace/name
patches:
- patch: |-
    - op: replace
      path: /spec/channel
      value: bike-rental-app/bike-rental-app-channel
  target:
    kind: Subscription
- patch: |-
    - op: replace
      path: /spec/pathname
      value: http://gitea-ai-edge-rhoai-edge-acm.apps.rhoai-edge-acm-poc.rhaiseng.com/edge-user-1/ai-edge-gitops.git
  target:
    kind: Channel
