apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: bike-rental-app-

patches:
- patch: |-
    - op: replace
      path: /spec/template/metadata/name
      value: '{{name}}-bike-rental-app'
    - op: replace
      path: /spec/template/spec/source/path
      value: acm/odh-edge/apps/bike-rental-app
    - op: replace
      path: /spec/template/spec/destination/namespace
      value: bike-rental-app
    - op: replace
      path: /spec/template/metadata/annotations/apps.open-cluster-management.io~1ocm-managed-cluster-app-namespace
      value: openshift-gitops
  target:
    group: argoproj.io
    version: v1alpha1
    kind: ApplicationSet
- patch: |-
    - op: replace
      path: /spec/policy-templates/0/objectDefinition/metadata/name
      value: bike-rental-app-ns-has-argo-label
  target:
    group: policy.open-cluster-management.io
    version: v1
    kind: Policy

replacements:
- source:
    kind: Placement
    group: cluster.open-cluster-management.io
    fieldPath: metadata.name
  targets:
  - select:
      group: argoproj.io
      kind: ApplicationSet
    fieldPaths:
      - spec.generators.0.clusterDecisionResource.labelSelector.matchLabels.cluster\.open-cluster-management\.io/placement
- source:
    kind: Placement
    group: cluster.open-cluster-management.io
    fieldPath: metadata.name
  targets:
  - select:
      group: policy.open-cluster-management.io
      kind: PlacementBinding
    fieldPaths:
      - placementRef.name
- source:
    kind: Policy
    group: policy.open-cluster-management.io
    fieldPath: metadata.name
  targets:
  - select:
      group: policy.open-cluster-management.io
      kind: PlacementBinding
    fieldPaths:
      - subjects.0.name
- source:
    group: argoproj.io
    kind: ApplicationSet
    fieldPath: spec.template.spec.destination.namespace
  targets:
  - select:
      group: policy.open-cluster-management.io
      kind: Policy
    fieldPaths:
    - spec.policy-templates.0.objectDefinition.spec.object-templates.0.objectDefinition.metadata.name
