apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: observability-metrics-custom-allowlist
  files:
  - files/uwm_metrics.yaml
  options:
    disableNameSuffixHash: true
